name: Deploy to github pages

on: 
  push: 
    branches: 
    - main
    - dev

jobs:
  first_job:
    runs-on: ubuntu-latest
    # Environment variables should be declared, if there are multiple jobs, on each job!
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}

    steps:
    # Secrets are printed as *** by github, so no problem.
      - name: print-secret
        run: echo "${{ secrets.TOKEN }}"
      
        # Environment variables are public, can be accessed from github or printed.
      - name: print-env
        run: echo "${{ env.NODE_ENV }}"

