name: Deploy to github pages

on: 
  push: 
    branches: 
    - main
    - dev

jobs:
  first_job:
    runs-on: ubuntu-latest
    # Environment variables should be declared, if there are multiple jobs, on each job!
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}

    # Services, are docker containers that handle premaid solutions for database management or other common stuff. 
    services:
      redis:
        image: redis
        ports:
        - 6379:6379

    steps:
      # Secrets are printed as *** by github, so no problem.
      - name: print-secret
        run: echo "${{ secrets.TOKEN }}"
      
      # Environment variables are public, can be accessed from github or printed, they need to be declared on each job from the object vars
      - name: print-env
        run: echo "${{ env.NODE_ENV }}"

      # We can access the virtual machine and install elements manually using bash commands. 
      - name: instal redis-cli
        run: sudo apt-get update -y && sudo apt-get install redis-tools -y
      
      - name: test redis connection
        run: redis-cli -h localhost -p 6379 ping

      # In order to build the project, we can use a github action, that installs the dependencies necesary to run the application, in this case node.js
      - name: node-setup
        # Keyword to use and action is uses, actionsRepository / action-name @ version
        uses: actions/setup-node@v4
        with: 
          node-version: '18'

      # Checkout, copies the application folder and locates the bash terminal on the root. 
      - name: Checkout
        uses: actions/checkout@v4

      # Then, we since we already installed node, and have our application, we can install dependencies and run tests.
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Step after test
        run: echo "if test fails, i should not be here."